### ISSUE TITLE
Is there a way to remove a worksheet?

### ISSUE THREAD

**Issue by kaufmanmatt** [weshatheleopard/rubyXL#193]
Hi, I am looking for something like workbook.worksheet_delete(name).  Wondering if this exists and I missed it or if it's easy to add.

**Comment by mezza** [comment]
Thanks for the gem. I see that in 3.3.10 tag you had a :remove_worksheet method. Can't see why this was removed. Any reason or just an omission?

**Comment by weshatheleopard** [comment]
Hint #1: 

> workbook.worksheets.class
 => Array

Hint #2:

http://ruby-doc.org/core-2.2.3/Array.html#class-Array-label-Removing+Items+from+an+Array

**Comment by odedd** [comment]
Following your hint, if I understood it correctly, it seems that after deleting a sheet using:
```
file = RubyXL::Parser.parse(file.path)
file.worksheets.delete(file['data_sets'])
```
Then later, when I open the modified file in Excel I get a "We found a problem with some content in..." error. That does not happen if I do not delete that sheet.

When I click "yes" and look at the generated error report it says:
> Removed Feature: Named range from /xl/workbook.xml part (Workbook) removed

Any ideas?

**Comment by iToshk** [comment]
Like @odedd says when I delete needless sheets in the ruby program from a template which included footer info and set print header title for rows, I got the same error.

Maybe because of footer settings or print header settings is still remain in?
I'm looking for the way to solve this issue, too.

**Comment by weshatheleopard** [comment]
The particular error you are getting is because the named range you have in your spreadsheet addresses a cell from the sheet you just deleted. Excel can (and must) validate referential integrity of its data, and so it does delete the names in such case. However, `rubyXL` is *not* a recreation of Excel in Ruby, and has its own limitations — for example, it does *not* validate referential integrity of a workbook. Unfortunately, I just do not have enough time to implement the entire functionality of Excel in Ruby!
