### ISSUE TITLE
Fatally high memory usage when opening large spreadsheets

### ISSUE THREAD

**Issue by duncan-bayne** [weshatheleopard/rubyXL#199]
Repro steps:

1) Create a simple workbook with several worksheets, and around a million total rows.  The resultant .xlsx file is around 27MiB in size.

2) Open it with the following code:

```
require 'rubyXL' 
doc = RubyXL::Parser.parse('large.xlsx')
```

3) Observe the Ruby process consumes all available RAM on the system (6.2GiB), then the system locks up necessitating a hard reboot.  Presumably it's paging like mad as the drive light is constantly on.

Details:

ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
rubyXL (3.3.12)
nokogiri (1.6.6.2)
rubyzip (1.1.7)

**Comment by weshatheleopard** [comment]
Don't think I can do much about it, it's mostly about ```nokogiri``` which isn't very frugal about its RAM usage...

**Comment by skippy** [comment]
nokogiri does offer a streaming interface.  I've had pretty good luck using it to keep memory low and consistent in other projects.  It isn't difficult to use, but it could be non-trivial based upon how the codebase is setup outside of nokogiri

**Comment by weshatheleopard** [comment]
@skippy: can you link me to example / manual?

**Comment by skippy** [comment]
you bet.  This article gives a nice summary: https://viget.com/extend/parsing-big-xml-files-with-nokogiri

For an internal project I had used the Reader approach.  More details can be found here: https://github.com/sparklemotion/nokogiri/wiki/Cheat-sheet#reader-parsers

btw, I started using your gem.  quite handy!  thank you kindly (right now my xlsx parsing needs are small, but I may be running into this issue as well... so I'll see if I can take a look at making this use streams)

**Comment by duffyjp** [comment]
We solved this at my organization by adding 64gigs of ram to the server.  Parsing all the data out of our 10.5MB xlsx file is still frustratingly slow at almost 30 minutes.

I wonder for those of us doing a one-way transaction if there isn't a better way.  I need to read a user generated XLSX file, import the data and that's it.  I never need to update that file or even export back to excel from my imported data. I'm betting a lot of the memory and processing time is pushing around all that excel metadata in memory I'll never use.

I'm still using ```extract_data``` so maybe that's part of my problem, but I chose this gem for it's user friendliness.  It wasn't deprecated at the time, and it really is user friendly.  

```ruby
ws.extract_data.first
[DEPRECATION] `extract_data` is deprecated.  Please access data directly by iterating through .sheet_data.rows
 => ["Provider ID", "Period", "Name", "Title"] 
```

```ruby
 ws.sheet_data.rows.first
```
<img width="1258" alt="screen shot 2016-01-29 at 3 20 33 pm" src="https://cloud.githubusercontent.com/assets/382216/12688478/20057886-c69c-11e5-9616-41d2dc5aed82.png">
whoa.

**Comment by weshatheleopard** [comment]
@duffyjp: 

1.  I am using Ruby's default `inspect`, as it does the job, and re-implementing it was never a huge priority. We are doing Open Source here, feel free to submit your Pull Request if you can come up with something you think is more suitable.
2. You certainly are wasting a lot of time by using `extract_data`; you should instead just directly pluck the values you need from the rows/cells. The example of the code that does that (in fact, that's pretty much the exact code that lived inside `extract_data`, minus all the memory allocation stuff) is in the README, section "Table reading".
3. I am thinking about maybe limiting the set of metadata that we should read, but the problem is, it is rather hard to figure out what exactly can be safely omitted. For example, you *have* to load stylessheet in order to properly process date cells, and so on.

**Comment by weshatheleopard** [comment]
@skippy: I'm looking into the reader-parsers, and it looks like exactly what I need, but I can't really grok the details of how to use them. Can you direct me to a bit of example code with in-depth tree navigation?

**Comment by duffyjp** [comment]
We've been experiencing random fatal memory consumption.  It's hard to reproduce, the same file can import fine 10 times in a row then explode.

Note in this graph the server has 64GB ram.  It was grinding an additional 17GB of swap when we intervened.  We had to restart apache to kill the runaway process.
![screen shot 2016-03-17 at 3 16 37 pm](https://cloud.githubusercontent.com/assets/382216/13859819/4f04c7b8-ec53-11e5-886d-373cd2e8d593.png)

The xlsx file has 38,000 total cells with content and is around 10MB.  Unfortunately it's not content I can release for debugging purposes.

**Comment by duffyjp** [comment]
I found another example from before we increased swap from 16 to 128GB (yeah, I know).  This one actually exhausted swap and triggered oom killer, but the box was totally unresponsive by that point.  Our sysadmin had to REISUB the machine.  

![screen shot 2016-03-17 at 3 39 53 pm](https://cloud.githubusercontent.com/assets/382216/13860503/9d050e2a-ec56-11e5-8270-6f611fce0b2a.png)

I wish I had an explanation for the spike, I never found anything interesting in the logs, rails or apache or otherwise.  

Here is a successful import: 
![screen shot 2016-03-17 at 3 54 13 pm](https://cloud.githubusercontent.com/assets/382216/13860884/93780e5a-ec58-11e5-8f15-edc0a6852352.png)

An interesting thing to note here is the import only took 27 minutes, but it hangs onto a lot of ram for hours.  Not sure why.  You can see when things go fine the memory usage is actually pretty modest.

Just for fun, here's a graph from when we had only 16GB ram: 
![screen shot 2016-03-17 at 3 58 12 pm](https://cloud.githubusercontent.com/assets/382216/13861018/2641cffa-ec59-11e5-9fe1-35f7a12d0f2c.png)

**Comment by simonfranzen** [comment]
I run into similar problems with memory. We only have 1 Heroku Worker with 1024RAM and I want to write 60k lines ~(7MB) into a XLSX Worksheet. I already improved the data preparation with `find_in_batches`, but this only solved my memory issues for generating XLS and CSV files.

I don't know if I can trust my numbers, but in the end I call workbook.stream and the memory goes up to 2492.18 MB

So what to do?

**Comment by duffyjp** [comment]
@simonfranzen are you modifying an existing excel file or creating a new one?  If you can get away with only generating brand-new files [axlsx](https://github.com/straydogstudio/axlsx_rails) can be surprisingly efficient.  

That said, I'm starting on a new project that will be creating reports 10x the size of what we've been doing in the past.  It's still within the realm of "reasonable" but I'll be exploring all options.  Including "can you live with a CSV file?"  :)

**Comment by simonfranzen** [comment]
@duffyjp Thanks for the reply. We are lucky this time: Client is fine with CSV and XLS. The XLSX option was defined in the past but now they don't need it anymore.

"I'm starting on a new project that will be creating reports 10x the size of what we've been doing in the past" 👍

**Comment by tomlobato** [comment]
Same here. With .includes and find_in_batch when querying DB it got better, but memory explodes on rubyXL .write.
I will try the approach: write to tsv and then ssconvert (from linux gnumeric) to xslx/xls.
I come back to let you know the results.

**Comment by duffyjp** [comment]
@tomlobato I don't know if it fits your use case, but check out https://github.com/paxa/fast_excel.  I use it to export DB data to excel for users to download.   It's an FFI to a C excel library, so all the heavy lifting is really efficient.  If you're careful to avoid N+1 queries it's basically instantaneous.  

It's write only, but I put my foot down at work and veto all Excel imports now. :D

**Comment by tomlobato** [comment]
> @tomlobato I don't know if it fits your use case, but check out https://github.com/paxa/fast_excel. I use it to export DB data to excel for users to download. It's an FFI to a C excel library, so all the heavy lifting is really efficient. If you're careful to avoid N+1 queries it's basically instantaneous.
> 
> It's write only, but I put my foot down at work and veto all Excel imports now. :D

that sounds great, I will try too. Thks!

**Comment by duncan-bayne** [comment]
Closing this since it's been ~ 8 years.
