### ISSUE TITLE
Can't disable warning messages.

### ISSUE THREAD

**Issue by spilin** [weshatheleopard/rubyXL#235]
Hi.

While running test suite we get alot of flood messages from here: https://github.com/weshatheleopard/rubyXL/blob/2e240407f7af84ee508ab67cda2b35b70bcc8e42/lib/rubyXL/objects/relationships.rb#L84-L87

Could we perhaps implement a logger with levels(warn, error, info, etc..) to avoid this flood while running tests or when we don't actually care about warnings. I could help with implementing logger, or any other solution you think fits best.

Tnx in advance.

**Comment by weshatheleopard** [comment]
These warnings mean that you are encountering some files that contain stuff `rubyXL` is not familiar with, which should prompt the users to do exactly what you did: report them here.

Please paste these messages here, and I'll make these objects known.

**Comment by spilin** [comment]
Awesome, tnx. 

*** WARNING: storage class not found for docProps/core0.xml (http://schemas.openxmlformats.org/officeDocument/2006/relationships/metadata/core-properties)
WARNING: RubyXL::WorkbookRoot is not aware what to do with RubyXL::GenericStorageObject

Is this enough or do you need an actual file?

**Comment by weshatheleopard** [comment]
@spilin: In your particular case, the software you used to create your file violates the standard (see http://www.ecma-international.org/publications/standards/Ecma-376.htm. Namely [this document](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-376,%20Fourth%20Edition,%20Part%202%20-%20Open%20Packaging%20Conventions.zip) on page 90 clearly states that standard namespace for "Core Properties" file is: `http://schemas.openxmlformats.org/package/2006/metadata/core-properties`, whereas in your Excel file it's `http://schemas.openxmlformats.org/officeDocument/2006/relationships/metadata/core-properties`.

So I would recommend that you *first* file a bug with the creators of the software who made that file (because clearly that's **they** who violate the standard, not `rubyXL`), and only if they refuse to fix that bug can workaround be considered (as you know, trying to accommodate for others' bugs is not a very productive strategy.)

**Comment by weshatheleopard** [comment]
@bigmountainben Your statement "same result" doesn't make it immediately obvious -- same as **what**. Please attach the offending file so I can investigate.
