### ISSUE TITLE
get worksheet by name and Excel's 31 character sheet name limit

### ISSUE THREAD

**Issue by MatthewSteen** [weshatheleopard/rubyXL#280]
Excel has a 31 character limit on worksheet names. However, to [access a worksheet by name](https://github.com/weshatheleopard/rubyXL#accessing-a-worksheet) rubyXL requires the full length name. Suggest either updating the code or documentation to clarify.

**Comment by weshatheleopard** [comment]
Since, as you rightfully mention, Excel only supports 31-character names, it is not possible to create such file in Excel. It is not possible to create such file in `RubyXL` wither, as it truncates the name before saving. I cannot control how *other* software packages deal with this file. So all in all, I believe current behavior is correct and intuitive. If you disagree, we can discuss.
