### ISSUE TITLE
How to delete a sheet?

### ISSUE THREAD

**Issue by khmunkhbat** [weshatheleopard/rubyXL#288]
When i delete sheet like below, workbook(xlsx template) is broke.
workbook.worksheets.delete_at(1)

How to solve this problem?

**Comment by weshatheleopard** [comment]
The workbook may be broken because at the moment `rubyXL` does not handle referential integrity and other sheets may be referencing cells from the deleted sheet. When Excel tries to follow the references to those cells, it gets confused. 

Basically, the answer is not to use the spreadsheets that cannot be handled by `rubyXL` in a manner that is not currently supported. It should be noted that `rubyXL` is geared first and foremost towards *reading* data from existing spreadsheets rather than *writing* data to them. As such, you always take risks when you do so.

In order to completely support *writing*, a lot of work needs to be done (effectively re-iplementing Excel in Ruby) and I do not have time for that :(
