### ISSUE TITLE
How to protect a sheet?

### ISSUE THREAD

**Issue by lporras** [weshatheleopard/rubyXL#289]
Hey guys,

Nice work on this gem!.  I need a way to protect a given sheet of my excel file, I found that the gem has this module: ```RubyXL::WorksheetProtection``` and I'm trying to use it like this:

```ruby
workbook = RubyXL::Workbook.new
worksheet = workbook.add_worksheet('Example')
worksheet.sheet_protection =  RubyXL::WorksheetProtection.new(
  password: "myPassword",
  sheet: true,
  objects: true,
  scenarios: true,
  formatCells: true,
  formatColumns: true,
  insertColumns: true,
  deleteColumns: true,
  insertRows: true,
  deleteRows: true
)
workbook.write("/tmp/protected_sheet.xlsx")
```

Then I opened the file and the sheet 'Example' was in fact protected, but a user can remove the protection just by right-clicking and selecting the option to unprotect the sheet, without writing any password!  Please I need help with this.

Also I want to hide the Worksheet

**Comment by weshatheleopard** [comment]
`password` value needs the hash of the password, not the direct value of the password. See https://www.openoffice.org/sc/excelfileformat.pdf pp. 114-116. I'm going to implement a respective convenience method in a couple minutes.

**Comment by weshatheleopard** [comment]
See https://github.com/weshatheleopard/rubyXL/blob/master/lib/rubyXL/convenience_methods.rb#L199

**Comment by lporras** [comment]
Thanks @weshatheleopard , how would I have to use that method?

**Comment by weshatheleopard** [comment]
Instead of `password: "myPassword",` you use `password: workbook.password_hash("myPassword"),

**Comment by lporras** [comment]
thanks it worked! @weshatheleopard.

In other hand, I'm wondering if there could be a method on worksheet called 'protect' that could receive the password and some options to protect the sheet, instead of using 'sheet_protection' directly.  This method could create the new instance of RubyXL::WorksheetProtection and set the password using the 'password_hash' method.  It would be similar to how this gem implemented this:
http://cxn03651.github.io/write_xlsx/worksheet.html#protect.

What do you think?

**Comment by weshatheleopard** [comment]
@lporras:
1) as you might know, the password hash is used in multiple places, not just in sheet protection.
2) password hash is **not** the only way to protect the spreadsheet; there are other ways (see https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.sheetprotection(v=office.14).aspx)

So I'm having the same problem as always: every now and then somebody comes to me and asks "can you implement X", where X sounds extremely easy at first, but as I start researching it, it progressively turns out more and more complex. And the problem is, that every person has a different X, so in the end in order to properly implement all the X'es I basically need to re-implementing the entire functionality of Excel in Ruby, and I just have no time to do that as I happen to have job and life.

On the other hand, if *you* are willing to implement the handling of passwords with all its complexity, be my guest and submit a pull request and I will be very likely to incorporate it if it is sufficiently well developed.
