### ISSUE TITLE
How to get formatted text (RTF) from the cell?

### ISSUE THREAD

**Issue by leshik** [weshatheleopard/rubyXL#327]
Hello,

In case the text inside one cell has different format (color, bold, etc.) is it possible to get it as is (not plain), with all the styles associated?

**Comment by ufo2mstar** [comment]
Looking for the same.. Am looking to see if Libraries like https://github.com/voxmedia/rich-text-ruby or https://github.com/senny/sablon will help us with that.. let's see what @weshatheleopard has to say about this feature that we may be missing

**Comment by weshatheleopard** [comment]
Of course you can — the problem is, it most likely will not be in the format you expect it to be. 

For example:

```
> cell = workbook[0][0][0]
> cell.datatype
=> "s"  # Shared String
>  workbook.shared_strings_container[cell.raw_value.to_i]
```

**Comment by ufo2mstar** [comment]
Haha, yes, once I RubyXL-parsed in a manually formatted cell I was spending a lot of time trying to understand the inspected value I got in futility! 😓 

I was debugging and playing around with the value in feeding the format in, but it may require some trial and error attempts without me completely understanding the problem here.

So is it the case @weshatheleopard that even feed in a new line character into cell strings is currently not possible?

**Comment by weshatheleopard** [comment]
Once again: we can. It will simply require quite some effort :tongue: 

It will probably something similar to [this](https://documentation.devexpress.com/OfficeFileAPI/114778/Excel-Export-Library/Examples/Formatting/How-to-Apply-Rich-Formatting-to-the-Cell-Text)

**Comment by ufo2mstar** [comment]
Got it! thanks for the [link](https://documentation.devexpress.com/OfficeFileAPI/114778/Excel-Export-Library/Examples/Formatting/How-to-Apply-Rich-Formatting-to-the-Cell-Text) and direction @weshatheleopard ..
Hmmm 🤔 let me finish my current task and take a look at this some time.
If I figure out something, will update here.. Cheers!
