### ISSUE TITLE
semantic versioning

### ISSUE THREAD

**Issue by CJKinni** [weshatheleopard/rubyXL#334]
It would be nice if rubyXL either followed  [semantic versioning](https://semver.org/) or made it clear in its README that it didn't.  I suspect some of the confusion around the 3.4.0 changes would have been clearer if the breaking change had happened in a major version release.  I, and I suspect many others, have seen so many ruby gems using semantic versioning that I assume it's the norm and only lock to major versions, where breaking changes are the norm.

[RubyGems.org reccomends](https://guides.rubygems.org/patterns/#semantic-versioning) using semantic versioning.

Thanks for your great work on the project!

**Comment by CJKinni** [comment]
Sorry for immediately opening and closing an issue -- I hit enter and the issue was created without me meaning to.

**Comment by weshatheleopard** [comment]
@CJKinni thanks for the link, I was not aware of this convention. The convention that I use is similar (MAJOR, major rewrites; MINOR, significant upgrades that *may* involve API changes; PATCH, fixes that should not affect compatibility). Since the inception of `RubyXL` it went through quite a few changes that would warrant a change of MAJOR, so I'm not sure if it's a good idea to use the "semantic versioning" as described, but I don't have a problem with that.
