### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by mainameiz** [weshatheleopard/rubyXL#345]
Hello everybody! First of all thanks to making such a great gem. It is very helpful :)

I have a couple of questions/suggestions:

1) Do you follow semver (https://semver.org/)?
2) Please, consider making a changelog/history file. It will help other people to upgrade between versions more convenient. There is a great guide about how to make a helpful changelog file - https://keepachangelog.com/.

Thanks a lot. It is a really really handy :)

**Comment by weshatheleopard** [comment]
1. I am *trying* to follow that ruleset, but in order to avoid inevitable mistakes and following complaints like "but you said that you do follow it, but in fact you don't!!!111" I do not explicitly declare so.
2. I do not a) consider duplication to be useful (if you REALLY need to see what's changed, use `git diff`), and b) do not have time to write the same thing I just wrote in Ruby, in human language -- that's doubling the work, you know.

As always, this is free software; if you want to help me -- join the project.
