### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by berpergian** [weshatheleopard/rubyXL#361]
Hi, I'm trying to import excel data and we will not know how many row the data will have and the problem is i can't check if the next row is ```nil``` or empty

Here's the code
```
def import(file)
      i = 1
      j = 0
      cell = []
      wb = RubyXL::Parser.parse(file)
      ws = wb[0]
      loop do
        #Looping to get data from excel
        cell[j] = [ws.sheet_data[i][0].value,ws.sheet_data[i][1].value,ws.sheet_data[i][2].value,
                  ws.sheet_data[i][3].value,ws.sheet_data[i][4].value,ws.sheet_data[i][5].value,ws.sheet_data[i][6].value]
        i = i + 1
        j = j + 1
        #check if end of data
        break if ws.sheet_data[i][0].value.nil? 
      end
      cell
    end
```

This is the example [Book1.xlsx](https://drive.google.com/file/d/1clxf1GxvVvbl0tkDybksAE67z6enNvpE/view?usp=sharing) and i using RubyXL ```3.3.31```
I already read #58 and #329 and still don't understand

**Comment by berpergian** [comment]
**What i have done**

- Restarting the Rails
- Static loop (its works, read 10 row data and get half of data)

**Comment by berpergian** [comment]
**UPDATE**

So i decided to use ```.count``` method and loop using normal ```for``` loop
I will close this issue but i still prefer using my first way, if you can give me advice what's wrong with my first way.

**Comment by weshatheleopard** [comment]
```
ws = wb[0]
ws.rows.each { |row|
  next if row.nil?
  ...your code doing whatever you need to do...
}
```

Seriously, this question does not seem like it has anything to do with this particular gem, it's just basic programming. Sorry, I just don't have time to educate every person on the internet, I have a job.

**Comment by vpibano** [comment]
I was searching for a way to check if the entire row of cells are empty and landed here.

The `row.nil?` didn't work on my end so I end up mapping the entire row cells' `value` and if they are all `nil` then it should return `[nil]` after `uniq` invocation. Then I can just use that exact value in `eql?`

```ruby
ws = wb[0]
ws.rows.each { |row|
  next if row.cells.map(&:value).uniq.eql?([nil])
  # ...your code doing whatever you need to do...
}
```

**Comment by weshatheleopard** [comment]
@vpibano Once again, seriously, every time you touch any object, you MUST assume it can be `nil`. It's called "[defensive programming](https://en.wikipedia.org/wiki/Defensive_programming)". Hoping that everything will always be done _for_ you and you can just rest on your laurels and do nothing but reap the benefits is very childish. _"Oh why didn't you all remove all the thorns from my path and make it perfectly safe for me so I can just bounce around happily without ever looking under my feet?"_

In your particular situation, you can do, for example, `row.compact.empty?` will return `true` if there are no non-`nil` cells in the row, and `false` otherwise. (But prior to that, you STILL must be mindful of the possibility that `row` itself may be `nil`).

**Comment by vpibano** [comment]
@weshatheleopard My bad for lacking details. This is the object that I get from `row`

```ruby
#<RubyXL::Row:0x000000010dbf50f0
 @cells=
  [
   #<RubyXL::Cell(7,1): nil, datatype=nil, style_index=22>,
   #<RubyXL::Cell(7,2): nil, datatype=nil, style_index=1>,
   ...
   #<RubyXL::Cell(7,71): nil, datatype=nil, style_index=1>,
   #<RubyXL::Cell(7,72): nil, datatype=nil, style_index=1>],
...
```

`row.nil?` returns `false` and `row.compact.blank?` throws `NoMethodError: undefined method compact`

Which is why I came up with the above code. 

Then I just discovered that some spreadsheets return this too
```ruby
=> #<RubyXL::Row:0x000000010dbf50f0
 @cells=
  [nil,
   nil,
   #<RubyXL::Cell(7,2): nil, datatype=nil, style_index=22>,
   #<RubyXL::Cell(7,3): nil, datatype=nil, style_index=22>,
   nil,
   #<RubyXL::Cell(7,5): nil, datatype=nil, style_index=12>,
   nil,
...
```

I see your point and it is indeed a much better approach. The `compact` makes it easily understandable at glance too. Thank you! With those all in mind, I end up with:

```ruby
ws = wb[0]
ws.rows.each { |row|
  next if row.nil? || row.cells.map{ |cell| cell&.value }.compact.nil?
  # ...your code doing whatever you need to do...
}
```

**Comment by weshatheleopard** [comment]
My apologies, I actually ment to write `row.cells.compact.blank?`.
